
package Presentation;

import Data.Utilidades;
import java.awt.BorderLayout;

/**
 *
 * @author eefre
 */
public class DigitadorScreen extends javax.swing.JFrame {

    /**
     * Creates new form DigitadorScreen
     */
    public DigitadorScreen() {
        initComponents();
        Utilidades.cerrarTodasLasVentanas();

        // Agregar esta ventana a la lista de ventanas abiertas
        Utilidades.abrirNuevaVentana(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftSidePanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnUsers = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        lblCopyRight = new javax.swing.JLabel();
        lblGoback = new javax.swing.JLabel();
        btnFincas = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSignOut = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        lblWelcomeIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftSidePanel.setBackground(new java.awt.Color(16, 23, 27));
        leftSidePanel.setForeground(new java.awt.Color(0, 255, 204));

        lblWelcome.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Bienvenido");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        btnUsers.setBackground(new java.awt.Color(0, 142, 73));
        btnUsers.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(51, 51, 51));
        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        btnUsers.setText("       Boleta                    ");
        btnUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        btnUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUsersKeyPressed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(0, 142, 73));
        btnProveedores.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(51, 51, 51));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Proveedores.png"))); // NOI18N
        btnProveedores.setText("        Inmersión             ");
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        lblCopyRight.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblCopyRight.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyRight.setText("Power by Evan | 2024");

        lblGoback.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lblGoback.setForeground(new java.awt.Color(255, 255, 255));
        lblGoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/goBackRed.png"))); // NOI18N
        lblGoback.setText("   Ir Atrás   ");
        lblGoback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGoback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGobackMouseClicked(evt);
            }
        });

        btnFincas.setBackground(new java.awt.Color(0, 142, 73));
        btnFincas.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnFincas.setForeground(new java.awt.Color(51, 51, 51));
        btnFincas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fincas.png"))); // NOI18N
        btnFincas.setText("    Empaque/Palletizado");
        btnFincas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFincas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFincasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftSidePanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLogo)
                                    .addComponent(lblWelcome)))
                            .addGroup(leftSidePanelLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCopyRight)
                                    .addComponent(lblGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFincas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblLogo)
                .addGap(43, 43, 43)
                .addComponent(lblWelcome)
                .addGap(46, 46, 46)
                .addComponent(btnUsers)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores)
                .addGap(18, 18, 18)
                .addComponent(btnFincas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblGoback)
                .addGap(35, 35, 35)
                .addComponent(lblCopyRight)
                .addGap(172, 172, 172))
        );

        getContentPane().add(leftSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        headerPanel.setBackground(new java.awt.Color(0, 142, 73));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dashboard de Digitador");

        lblSignOut.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblSignOut.setForeground(new java.awt.Color(0, 0, 0));
        lblSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/personOut.png"))); // NOI18N
        lblSignOut.setText("Cerrar Sesión");
        lblSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(323, 323, 323)
                .addComponent(lblSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1080, 80));

        bodyPanel.setBackground(new java.awt.Color(16, 23, 27));
        bodyPanel.setForeground(new java.awt.Color(255, 255, 255));

        lblWelcomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/digitador.png"))); // NOI18N

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(lblWelcomeIcon)
                .addContainerGap(487, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(lblWelcomeIcon)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        getContentPane().add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1080, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked

        HomeScreenDigitador scr = new HomeScreenDigitador();
        scr.setLocationRelativeTo(null);
        scr.setVisible(true);
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        JpanelBoleta panel = new JpanelBoleta();
        panel.setSize(1130, 660);
        panel.setLocation(0, 0);
        bodyPanel.removeAll();
        bodyPanel.add(panel, BorderLayout.CENTER);
        bodyPanel.revalidate();
        bodyPanel.repaint();
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUsersKeyPressed

    }//GEN-LAST:event_btnUsersKeyPressed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed

    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void lblGobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGobackMouseClicked

        HomeScreenDigitador scr = new HomeScreenDigitador();
        scr.setLocationRelativeTo(null);
        scr.setVisible(true);
    }//GEN-LAST:event_lblGobackMouseClicked

    private void btnFincasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFincasActionPerformed

    }//GEN-LAST:event_btnFincasActionPerformed

    private void lblSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignOutMouseClicked
        LoginScreen scr = new LoginScreen();
        scr.setLocationRelativeTo(null);
        scr.setVisible(true);
    }//GEN-LAST:event_lblSignOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigitadorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigitadorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigitadorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigitadorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DigitadorScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnFincas;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnUsers;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCopyRight;
    private javax.swing.JLabel lblGoback;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSignOut;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomeIcon;
    private javax.swing.JPanel leftSidePanel;
    // End of variables declaration//GEN-END:variables
}
