
package Presentation;

import Data.Utilidades;

/**
 *
 * @author eefre
 */
public class ReportsScreen extends javax.swing.JFrame {

    /**
     * Creates new form ReportsScreen
     */
    public ReportsScreen() {
        initComponents();
        Utilidades.cerrarTodasLasVentanas();

        // Agregar esta ventana a la lista de ventanas abiertas
        Utilidades.abrirNuevaVentana(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSignOut = new javax.swing.JLabel();
        leftSidePanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnUsers = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        lblCopyRight = new javax.swing.JLabel();
        lblGoback = new javax.swing.JLabel();
        btnFincas = new javax.swing.JButton();
        btnFincas1 = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(16, 23, 27));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 23, 27));

        headerPanel.setBackground(new java.awt.Color(0, 142, 73));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seccion de Reportes");

        lblSignOut.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblSignOut.setForeground(new java.awt.Color(0, 0, 0));
        lblSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/personOut.png"))); // NOI18N
        lblSignOut.setText("Cerrar Sesión");
        lblSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343)
                .addComponent(lblSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        leftSidePanel.setBackground(new java.awt.Color(16, 23, 27));
        leftSidePanel.setForeground(new java.awt.Color(0, 255, 204));

        lblWelcome.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Seleccione una opción");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        btnUsers.setBackground(new java.awt.Color(0, 142, 73));
        btnUsers.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(51, 51, 51));
        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resultIcon.png"))); // NOI18N
        btnUsers.setText("   Empaques / dia              ");
        btnUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        btnUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUsersKeyPressed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(0, 142, 73));
        btnProveedores.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(51, 51, 51));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resultIcon.png"))); // NOI18N
        btnProveedores.setText("      Pallest / Dia                  ");
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        lblCopyRight.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblCopyRight.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyRight.setText("Power by Evan | 2024");

        lblGoback.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lblGoback.setForeground(new java.awt.Color(255, 255, 255));
        lblGoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/goBackRed.png"))); // NOI18N
        lblGoback.setText("   Ir Atrás   ");
        lblGoback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGoback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGobackMouseClicked(evt);
            }
        });

        btnFincas.setBackground(new java.awt.Color(0, 142, 73));
        btnFincas.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnFincas.setForeground(new java.awt.Color(51, 51, 51));
        btnFincas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resultIcon.png"))); // NOI18N
        btnFincas.setText("  Proveedor Fruta / dia   ");
        btnFincas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFincas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFincasActionPerformed(evt);
            }
        });

        btnFincas1.setBackground(new java.awt.Color(0, 142, 73));
        btnFincas1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnFincas1.setForeground(new java.awt.Color(51, 51, 51));
        btnFincas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/resultIcon.png"))); // NOI18N
        btnFincas1.setText("   % Rechazo / dia              ");
        btnFincas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFincas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFincas1ActionPerformed(evt);
            }
        });

        bodyPanel.setBackground(new java.awt.Color(16, 23, 27));

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblLogo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFincas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFincas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSidePanelLayout.createSequentialGroup()
                                .addComponent(lblWelcome)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSidePanelLayout.createSequentialGroup()
                                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCopyRight)
                                    .addComponent(lblGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblLogo)
                .addGap(43, 43, 43)
                .addComponent(lblWelcome)
                .addGap(46, 46, 46)
                .addComponent(btnUsers)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores)
                .addGap(18, 18, 18)
                .addComponent(btnFincas)
                .addGap(18, 18, 18)
                .addComponent(btnFincas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGoback)
                .addGap(35, 35, 35)
                .addComponent(lblCopyRight)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSidePanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFincasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFincasActionPerformed

    }//GEN-LAST:event_btnFincasActionPerformed

    private void lblGobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGobackMouseClicked

        HomeScreen scr = new HomeScreen();
        scr.setLocationRelativeTo(null);
        scr.setVisible(true);
    }//GEN-LAST:event_lblGobackMouseClicked

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed

    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUsersKeyPressed

    }//GEN-LAST:event_btnUsersKeyPressed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed

    }//GEN-LAST:event_btnUsersActionPerformed

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked

        HomeScreen scr = new HomeScreen();
        scr.setLocationRelativeTo(null);
        scr.setVisible(true);
    }//GEN-LAST:event_lblLogoMouseClicked

    private void lblSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignOutMouseClicked
        LoginScreen scr = new LoginScreen();
        scr.setLocationRelativeTo(null);
        scr.setVisible(true);
    }//GEN-LAST:event_lblSignOutMouseClicked

    private void btnFincas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFincas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFincas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnFincas;
    private javax.swing.JButton btnFincas1;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnUsers;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCopyRight;
    private javax.swing.JLabel lblGoback;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSignOut;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel leftSidePanel;
    // End of variables declaration//GEN-END:variables
}
